[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
observable-maps = { path = "..", version = "0.1.0" }
rust_decimal = "1.17.0"
rust_decimal_macros = "1.17"